version: "3.9"

x-shared-env: &shared-env
  environment:
    NODE_ENV: ${NODE_ENV:-development}

services:
  infra0-visualizer-ui:
    <<: *shared-env
    build:
      context: .
      dockerfile: ui.dockerfile
    ports:
      - 3000:3000
    container_name: infra0-visualizer-ui
    image: xshubhamx/infra0-visualizer-ui:${NODE_ENV:-development}
    stop_signal: SIGINT

  mongo:
    <<: *shared-env
    image: mongo:latest
    container_name: infra0-mongo
    ports:
      - 27017:27017
    volumes:
      - infra0-mongo-data:/data/db
    restart: unless-stopped

  infra0-visualizer-server:
    <<: *shared-env
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - 4000:4000
    container_name: infra0-visualizer-server
    image: xshubhamx/infra0-visualizer-server:${NODE_ENV:-development}
    stop_signal: SIGINT
    depends_on:
      - mongo

volumes:
  infra0-mongo-data: